-- MySQL Script generated by MySQL Workbench
-- Fri Mar 15 15:37:33 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema trombi-mmi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trombi-mmi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trombi-mmi` DEFAULT CHARACTER SET utf8 ;
USE `trombi-mmi` ;

-- -----------------------------------------------------
-- Table `trombi-mmi`.`formation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trombi-mmi`.`formation` (
  `formation_id` INT(11) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`formation_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `trombi-mmi`.`class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trombi-mmi`.`class` (
  `class_id` INT(11) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `formation_id` INT(11) NOT NULL,
  PRIMARY KEY (`class_id`, `formation_id`),
  INDEX `fk_class_formation_idx` (`formation_id` ASC) ,
  CONSTRAINT `fk_class_formation`
    FOREIGN KEY (`formation_id`)
    REFERENCES `trombi-mmi`.`formation` (`formation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `trombi-mmi`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trombi-mmi`.`student` (
  `person_id` INT(11) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `position` VARCHAR(255) NULL DEFAULT NULL,
  `photo_url` VARCHAR(255) NULL DEFAULT NULL,
  `class_class_id` INT(11) NOT NULL,
  `class_formation_id` INT(11) NOT NULL,
  PRIMARY KEY (`person_id`),
  INDEX `fk_student_class1_idx` (`class_class_id` ASC, `class_formation_id` ASC) ,
  CONSTRAINT `fk_student_class1`
    FOREIGN KEY (`class_class_id` , `class_formation_id`)
    REFERENCES `trombi-mmi`.`class` (`class_id` , `formation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `trombi-mmi`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trombi-mmi`.`users` (
  `id` INT(11) NOT NULL,
  `email` VARCHAR(534) NOT NULL,
  `pass` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
